### ISSUE TITLE
I can't look amoad Native app ads (image+text, icon+text, text) in genymotion.

### ISSUE THREAD

**Issue by wangmingSCG** [amoad/amoad-android-sdk#100]
Hi,
I downloaded android sample project from github.(https://github.com/amoad/amoad-android-sdk)
I inserted my SID to sample code.
I runned it on my genymotion but I can't show real ads.
How can i show it on my genymotion?
Regards.

**Comment by wangmingSCG** [comment]
I am using genymotion 2.6 and
Virtual device: Sony Xperia Z - 4.3 - API 18

**Comment by wangmingSCG** [comment]
Can I use any test ID yours suggest?

**Comment by wangmingSCG** [comment]
Now I can look only text "AMoAdNativeAppIconTextSample" and "AMoAdNativeAppImageTextSample" on my Genymotion.

**Comment by wangmingSCG** [comment]
Please help me.

**Comment by manabernetes** [comment]
@wangmingSCG 

Please remind yourself that you have to choose the sample fit your ID.

AMoAdNativeAppTextSample for Text only.
AMoAdNativeAppIconTextSample for icon and text.
AMoAdNativeAppImageTextSample for icon, large image and text.

I'd like to know details about your account,
Could you contact us via our technical support department.

Thank you.

**Comment by manabernetes** [comment]
If the problem has not be resolved, please remind us.
